### ISSUE TITLE
Patient Dashboard

### ISSUE THREAD

**Issue by kgosi-gabaocwe** [freezy04/Runtime-Terror#10]
The card views on the patient dashboard don't take user anywhere, they're there for show.

**Comment by Dylan-Fasser** [comment]
Good Day 

Yeah, this is just a temporary measure, since the activities for the dashboards are still being created, I am not able to link anything as of yet, as the activities get created I will update the dashboard accordingly.

Thanks for bringing this up, I will update the dashboard(s) as soon as the activities are created for them.

I will close this Issue once all the links and activities have been created.
